# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      group: OLD_TS_WEB_RUNNER_GROUP
    steps:
      - uses: actions/checkout@v4

      - run: npm i -g corepack@latest &&corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      # Pick your own package manager and build script
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate
        env:
          NUXT_APP_BASE_URL: /nuxt3-base-layer/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.playground/.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on:
      group: OLD_TS_WEB_RUNNER_GROUP
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
